In [2]:
import numpy as np

# 1. Creating arrays
a = np.array([1, 2, 3, 4, 5])
print("1D Array:", a)

b = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", b)

# 2. Array of zeros and ones
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)

# 3. Range and linspace
arr_range = np.arange(0, 10, 2)
arr_lin = np.linspace(0, 1, 5)
print("\nRange Array:", arr_range)
print("Linspace Array:", arr_lin)

# 4. Array operations
x = np.array([10, 20, 30, 40])
y = np.array([1, 2, 3, 4])
print("\nAddition:", x + y)
print("Multiplication:", x * y)
print("Division:", x / y)

# 5. Matrix operations
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print("\nMatrix Multiplication:\n", np.dot(mat1, mat2))

# 6. Statistical functions
random_arr = np.random.randint(1, 100, 10)
print("\nRandom Array:", random_arr)
print("Mean:", np.mean(random_arr))
print("Standard Deviation:", np.std(random_arr))
print("Max:", np.max(random_arr))
print("Min:", np.min(random_arr))

# 7. Reshaping
reshaped = np.arange(1, 13).reshape(3, 4)
print("\nReshaped Array (3x4):\n", reshaped)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Range Array: [0 2 4 6 8]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]

Addition: [11 22 33 44]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]

Matrix Multiplication:
 [[19 22]
 [43 50]]

Random Array: [ 1 27 37 41 63 22 75 86 81 59]
Mean: 49.2
Standard Deviation: 26.62630278502819
Max: 86
Min: 1

Reshaped Array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
